export const BackgroundImages = {
    "/assets/backgrounds/used/Hedge.jpg": require("../assets/backgrounds/used/Hedge.jpg"),
    "/assets/backgrounds/used/Cloudy_Hills_Sunset.jpg": require("../assets/backgrounds/used/Cloudy_Hills_Sunset.jpg"),
    "/assets/backgrounds/used/Desert_Sunset.jpg": require("../assets/backgrounds/used/Desert_Sunset.jpg"),
    "/assets/backgrounds/used/Island_Sunset.jpg": require("../assets/backgrounds/used/Island_Sunset.jpg"),
    "/assets/backgrounds/used/Ocean_4.png": require("../assets/backgrounds/used/Ocean_4.png"),
    "/assets/backgrounds/used/Ocean_5.png": require("../assets/backgrounds/used/Ocean_5.png"),
    "/assets/backgrounds/used/Ocean_6.png": require("../assets/backgrounds/used/Ocean_6.png"),
    "/assets/backgrounds/used/Ocean_7.png": require("../assets/backgrounds/used/Ocean_7.png"),
    "/assets/backgrounds/used/Ocean_8.png": require("../assets/backgrounds/used/Ocean_8.png"),
    "/assets/backgrounds/used/Outer_Space.jpg": require("../assets/backgrounds/used/Outer_Space.jpg"),
    "/assets/backgrounds/used/Pixelated_Desert.jpg": require("../assets/backgrounds/used/Pixelated_Desert.jpg"),
    "/assets/backgrounds/used/Pixelated_Mountains.jpg": require("../assets/backgrounds/used/Pixelated_Mountains.jpg"),
    "/assets/backgrounds/used/Snowy_Mountain.jpg": require("../assets/backgrounds/used/Snowy_Mountain.jpg"),
    "/assets/backgrounds/used/Tall_Forest.jpg": require("../assets/backgrounds/used/Tall_Forest.jpg"),
    "/assets/backgrounds/used/The_Moon.jpg": require("../assets/backgrounds/used/The_Moon.jpg"),
    "/assets/backgrounds/used/Treetop_Forest.jpg": require("../assets/backgrounds/used/Treetop_Forest.jpg"),
    "/assets/backgrounds/used/Secret_Waterfall.jpg": require("../assets/backgrounds/used/Secret_Waterfall.jpg"),
};
