/*
 * 100% completely generated by Claude, given game.jsx and asked to refactor and isolate separate processes
*/

// components/game/GameHUD.jsx
import React from 'react';
import { StyleSheet } from 'react-native';
import { Text, FAB } from 'react-native-paper';

export default function GameHUD({ score, hp, duration, paused, onPausePress }) {
	const formatDuration = (ms) => {
		const totalSeconds = Math.floor(ms / 1000);
		const minutes = Math.floor(totalSeconds / 60);
		const seconds = totalSeconds % 60;
		return `${minutes}:${seconds.toString().padStart(2, '0')}`;
	};

	return (
		<>
			<Text style={styles.hp}>HP: {hp}</Text>
			<Text style={styles.score}>Score: {score}</Text>
			<Text style={styles.duration}>Playtime: {formatDuration(duration)}</Text>

			<FAB
				icon={paused ? 'close' : 'pause'}
				style={styles.pauseButton}
				onPress={onPausePress}
			/>
		</>
	);
}

const styles = StyleSheet.create({
	hp: {
		fontSize: 20,
		position: 'absolute',
		top: 10,
		left: 10,
	},
	score: {
		fontSize: 20,
		position: 'absolute',
		top: 30,
		left: 10,
	},
	duration: {
		fontSize: 20,
		position: 'absolute',
		top: 50,
		left: 10,
	},
	pauseButton: {
		position: 'absolute',
		right: 0,
		margin: 10,
		borderRadius: 100,
	},
});