/**
 * This code was largely pregenerated by Claude, given game.jsx, then slightly refactored
 */

// components/game/GameCanvas.jsx
import React from 'react';
import { StyleSheet, View, Image, Dimensions } from 'react-native';

const guy = require("../../assets/guy.png");
const bad_guy = require("../../assets/bad_guy.png");
 
export default function GameCanvas({ player, projectiles, enemies }) {
  return (
    <>
      {/* Player */}
      <Image
        style={[
          styles.player,
          {
            width: player.getWidth() * 2,
            height: player.getHeight(),
            left: player.getDisplayX(),
            top: player.getDisplayY(),
            transform: [{ rotate: `${player.rotation}deg` }],
          },
        ]}
        source={guy}
        resizeMode="contain"
      />

      {/* Projectiles */}
      {projectiles.map((p, i) => (
        <View
          key={`projectile-${i}`}
          style={[
            styles.projectile,
            {
              left: p.getDisplayX(),
              top: p.getDisplayY(),
            },
          ]}
        />
      ))}

      {/* Enemies */}
      {enemies.map((e, i) => (
        <Image
          key={`enemy-${i}`}
          style={[
            styles.enemy,
            {
              left: e.x,
              top: e.y,
              width: e.getWidth(),
              height: e.getHeight(),
            },
          ]}
          source={bad_guy}
        />
      ))}
    </>
  );
}

const styles = StyleSheet.create({
  player: {
    position: 'absolute',
  },
  projectile: {
    width: 10,
    height: 10,
    backgroundColor: 'black',
    borderRadius: 5,
    position: 'absolute',
  },
  enemy: {
    position: 'absolute',
  },
});