/*
 * 100% completely generated by Claude, given game.jsx and asked to refactor and isolate separate processes
*/

// components/game/PauseMenu.jsx
import React from 'react';
import { StyleSheet } from 'react-native';
import { Button, Portal } from 'react-native-paper';
import Wrapper from '@components/menu/Wrapper';

export default function PauseMenu({ visible, onResume, onQuit }) {
	if (!visible) return null;

	return (
		<Portal>
			<Wrapper
				style={styles.container}
				title="Paused"
				onClose={onResume}
				onOpen={() => console.log('Game Paused')}
			>
				<Button
					mode="outlined"
					icon="door-open"
					style={styles.button}
					labelStyle={styles.buttonText}
					onPress={onQuit}
				>
					Quit
				</Button>
			</Wrapper>
		</Portal>
	);
}

const styles = StyleSheet.create({
	container: {
		height: '100%',
	},
	button: {
		alignSelf: 'center',
		width: '45%',
	},
	buttonText: {
		fontSize: 28,
	},
});